apiVersion: v1
kind: Service
metadata:
  name: hanip-action
  namespace: hanip
  labels:
    app: hanip-action
spec:
  selector:
    app: hanip-action
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP