apiVersion: v1
kind: Service
metadata:
  name: hanip-actor
  namespace: app
  labels:
    app: hanip-actor
spec:
  selector:
    app: hanip-actor
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP